[14-Sep-2018 20:35:36 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(app\common\exception\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:14
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(14): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 14, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('app\\common\\exce...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\l in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 14
[14-Sep-2018 20:35:58 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(app\common\exception\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:14
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(14): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 14, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('app\\common\\exce...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\l in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 14
[14-Sep-2018 20:37:01 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(app\common\exception\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:14
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(14): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 14, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('app\\common\\exce...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\l in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 14
[14-Sep-2018 20:38:19 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(app\common\exception\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:14
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(14): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 14, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('app\\common\\exce...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\l in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 14
[14-Sep-2018 20:40:25 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:15
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(15): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 15, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 15
[14-Sep-2018 20:48:21 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
[14-Sep-2018 20:59:00 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
[14-Sep-2018 21:01:17 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
[14-Sep-2018 21:48:24 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
[14-Sep-2018 21:51:57 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
[14-Sep-2018 21:53:04 PST8PDT] PHP Fatal error:  Uncaught think\exception\ErrorException: Declaration of app\common\exception\ExceptionHandler::render(think\exception $e) should be compatible with think\exception\Handle::render(Exception $e) in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php:16
Stack trace:
#0 E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php(16): think\Error::appError(2, 'Declaration of ...', 'E:\\phpstudy\\PHP...', 16, Array)
#1 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(557): include('E:\\phpstudy\\PHP...')
#2 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Loader.php(58): think\__include_file('E:\\phpstudy\\PHP...')
#3 [internal function]: think\Loader::autoload('app\\common\\exce...')
#4 [internal function]: spl_autoload_call('app\\common\\exce...')
#5 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\Error.php(109): class_exists('\\app\\common\\exc...')
#6 E:\phpstudy\PHPTutorial\WWW\watchV2\thinkphp\library\think\E in E:\phpstudy\PHPTutorial\WWW\watchV2\application\common\exception\ExceptionHandler.php on line 16
